# 7	Working with Data (NumPy)

## installing NumPy 

In [2]:
#pip install numpy

Note: you may need to restart the kernel to use updated packages.


## importing NumPy to your programme 

In [3]:
import numpy as np


## Arrays

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [6]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5], 
    [5, 2, 3, 5, 4]
])
print(arr)

[[1 2 3 4 5]
 [5 2 3 5 4]]


In [8]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5], 
    [5, 2, 3, 5, 4]
])
print('The dimensions is: ',arr.ndim)
print ('The shape of the array is: ', arr.shape)

The dimensions is:  2
The shape of the array is:  (2, 5)


### Indexes 

In [10]:
import numpy as np

arr1D = np.array(['a', 'b', 'c'])
arr2D = np.array([
    [1, 2, 3, 4, 5], 
    [5, 2, 3, 5, 4] 
])

print('The first item of the 1D array is: ', arr1D[0])
print('The first item of the 2D array is: ', arr2D[0,0])

The first item of the 1D array is:  a
The first item of the 2D array is:  1


## Data Type 

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print (arr)
print(arr.dtype)

[1 2 3 4]
int32


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print (arr)
print (arr.shape)
arr2= arr.reshape(2,3)
print (arr2)
print(arr2.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [20]:
import numpy as np

arr2D = np.array([
    [1, 2, 3, 4, 5], 
    [5, 2, 3, 5, 4] 
])
print (arr2D)

arr1D = arr2D.reshape(-1)
print (arr1D)


[[1 2 3 4 5]
 [5 2 3 5 4]]
[1 2 3 4 5 5 2 3 5 4]


In [21]:
import numpy as np

arr2D = np.array([
    [1, 2, 3, 4, 5], 
    [5, 2, 3, 5, 4] 
])

for x in arr2D:
    print ('x = ', x)

x =  [1 2 3 4 5]
x =  [5 2 3 5 4]


In [22]:
import numpy as np

arr2D = np.array([
    [1, 2, 3, 4, 5], 
    [5, 2, 3, 5, 4] 
])

for x in arr2D:
    for y in x:
        print ('y = ', y)
        

y =  1
y =  2
y =  3
y =  4
y =  5
y =  5
y =  2
y =  3
y =  5
y =  4


In [23]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


Search in an array

In [24]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


Sort 

In [26]:
import numpy as np

arr =  np.array([1, 2, 3, 4, 5, 4, 4])

x = np.sort(arr)

print(x)

[1 2 3 4 4 4 5]


Random

In [33]:
import numpy as np

arr = np.random.randint(100, size=5)
print(arr)

arr2 = np.random.randint(100, size=(5,3))
print(arr2)


[54 56 34 78  9]
[[29 49 73]
 [74 69 11]
 [39 40 77]
 [94 58 59]
 [49 44 98]]


## Operations on Arrays 

In [38]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

res = np.add(arr1, arr2)
print('The result of Adding the arrays is: ', res)
res = np.subtract(arr1, arr2)
print('The result of Subtracting the arrays is: ', res)
res = np.multiply(arr1, arr2)
print('The result of Multiplying the arrays is: ', res)
res = np.divide(arr1, arr2)
print('The result of dividing the arrays is: ', res)
res = np.power(arr1, arr2)
print('The result of power the arrays is: ', res)
res = np.mod(arr1, arr2)
print('The result of mod the arrays is: ', res)

The result of Adding the arrays is:  [30 32 34 36 38 40]
The result of Subtracting the arrays is:  [-10 -10 -10 -10 -10 -10]
The result of Multiplying the arrays is:  [200 231 264 299 336 375]
The result of dividing the arrays is:  [0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
The result of power the arrays is:  [100 121 144 169 196 225]
The result of mod the arrays is:  [10 11 12 13 14 15]


In [39]:
import numpy as np

arr = np.arange(1, 11)
print (arr)

x = np.lcm.reduce(arr)

print(x)

[ 1  2  3  4  5  6  7  8  9 10]
2520


# Slicing

## ID 

In [1]:
import numpy as np
A = np.array([1, 2, 3, 4, 5, 6, 7])
print('A[1:4] ',A[1:4])
print('A[2:] ', A[2:])
print('A[:4] ', A[:4])
print('A[1:5:2] ', A[1:5:2])
print('A[::2]', A[::2])


A[1:4]  [2 3 4]
A[2:]  [3 4 5 6 7]
A[:4]  [1 2 3 4]
A[1:5:2]  [2 4]
A[::2] [1 3 5 7]


## 2D

In [2]:
import numpy as np
A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('A[1, 1:4] ', A[1, 1:4])
print('A[0:2, 1:4] ', A[0:2, 1:4])

A[1, 1:4]  [7 8 9]
A[0:2, 1:4]  [[2 3 4]
 [7 8 9]]


## Shape

In [4]:
import numpy as np
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(A.shape)

(2, 4)


## Reshape

In [5]:
import numpy as np
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
B = A.reshape(4, 3)
print(B)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Faltting

In [6]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A.reshape(-1)
print(B)

[1 2 3 4 5 6]


## Joining

In [9]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.concatenate((A, B))
D = np.concatenate((B, A))
E = np.concatenate((A, A))
F = np.concatenate((A, A, C))
print(C)
print(D)
print(E)
print(F)

[1 2 3 4 5 6]
[4 5 6 1 2 3]
[1 2 3 1 2 3]
[1 2 3 1 2 3 1 2 3 4 5 6]
